<?php

/**
 * @file
 * Module file for Forcontu Hello
 * Este módulo crea una página estática con un mensaje de bienvenida.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;

/**
 *  Implements hook_help().
 */
Function forcontu_hello_help($route_name, RouteMatchInterface $route_match) {

    switch ($route_name) {
        // Main module help for the Forcontu Hello module.
        case 'help.page.forcontu_hello':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This module shows how to create a simple page. ') . '</p>';
            return $output;
        // Help for another path in the Forcontu Hello module.
        case 'forcontu_hello.hello':
            $output = '';
            $output .= '<p>' . t('This is a very simple page created by the Forcontu Hello module. ') . '</p>';
            return $output;
    }

}

/**
 *  Implements hook_schema().
 */
function forcontu_hello_schema() {

}


/**
 * Implements hook_install().
 */
function forcontu_hello_install(){
    //1. Creación y asignación de una variable de estado
    \Drupal::state()->set('forcontu_hello.test', TRUE);

    //2. Creación de un término de taxonomía
    $term = Term::create(array(
        'name' => t('Forcontu Hello'),
        'vid' => 'tags',
    ));
    $term->save();
}

/**
 * Implements hook_uninstall().
 */
function forcontu_hello_uninstall(){
    \Drupal::state()->delete('forcontu_hello.test');
}