<?php

/**
 * Implements hook_theme().
 */

function myModule_theme($existing, $type, $theme, $path){
    return array(
        'registro' => array(
            'variables' => array(
                'titulo' => 'Registro',
                'descripcion' => NULL,
                'otraVariable' => NULL,
                'peliculas' => NULL,
            ),
            'template' => 'registro',
            //'render element' => 'children',
        ),
    );
}

function myModule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){

}
